# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "devlog"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["mihael"]
  s.date = "2014-08-15"
  s.description = "devlog.markdown time&space extractor"
  s.email = "kitschmaster@gmail.com"
  s.executables = ["devlog"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/devlog",
    "devlog.gemspec",
    "devlog.markdown",
    "empty_devlog.markdown",
    "lib/devlog.rb",
    "sublime_text/.DS_Store",
    "sublime_text/devlog.tmbundle/Snippets/begin.tmSnippet",
    "sublime_text/devlog.tmbundle/Snippets/combegin.tmSnippet",
    "sublime_text/devlog.tmbundle/Snippets/comend.tmSnippet",
    "sublime_text/devlog.tmbundle/Snippets/end.tmSnippet",
    "sublime_text/devlog.tmbundle/Snippets/link.tmSnippet",
    "sublime_text/devlog.tmbundle/Snippets/selfbegin.tmSnippet",
    "sublime_text/devlog.tmbundle/Snippets/selfend.tmSnippet",
    "sublime_text/devlog.tmbundle/Snippets/tu.tmSnippet",
    "sublime_text/devlog.tmbundle/info.plist",
    "sublime_text/tu.py",
    "test/devlog_test.rb",
    "test/test_helper.rb",
    "test_devlog.markdown",
    "test_negative_devlog.markdown",
    "test_single_devlog.markdown",
    "test_stats_devlog.markdown"
  ]
  s.homepage = "http://github.com/mihael/devlog"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.14"
  s.summary = "takes devlog.markdown and gives info"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.2"])
    else
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<activesupport>, ["~> 3.2"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<activesupport>, ["~> 3.2"])
  end
end

